#
# GNUmakefile for target LocalizationManager
# begin - generated by buildtool
#

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME= LocalizationManager

LocalizationManager_OBJC_FILES = LocalizationManager/main.m \
	LocalizationManager/MasterViewController.m \
	LocalizationManager/Helper/NSScrollView+MultiLine.m \
	LocalizationManager/Helper/StringsHandler.m \
	LocalizationManager/Helper/IRTextFieldDrag.m \
	LocalizationManager/AppDelegate.m 

LocalizationManager_C_FILES = 

LocalizationManager_CPP_FILES = 

LocalizationManager_OBJCPP_FILES = 

LocalizationManager_HEADER_FILES =

LocalizationManager_RESOURCE_FILES = LocalizationManager/MasterViewController.xib \
	LocalizationManager/Base.lproj/MainMenu.xib \
	LocalizationManagerInfo.plist 

ADDITIONAL_INCLUDE_DIRS += -I. \
	-I./LocalizationManager \
	-I./LocalizationManager/Helper 

ADDITIONAL_OBJC_LIBS =

include $(GNUSTEP_MAKEFILES)/application.make

#
# end - generated makefile
#
